apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: org-chart
  name: org-chart
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: org-chart
  type: ClusterIP
status:
  loadBalancer: {}
